name: Announce Report has been Submitted
description: Post this ticket to announce that you have submitted a report.
title: "[Report on task] Task number & Your team name here"
labels: ["report"]
projects: ["piasecday/3"]
assignees:
  - benjamsf
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Mink채 osateht채v채n raportti kyseess채
      description: Kirjoita alle. 
    validations:
      required: true