name: Announce Report
description: Post this ticket to announce that you have uploaded a Report. 
title: "[Report]: Task number & Your team name here"
labels: ["report"]
projects: ["piasecday/3"]
assignees:
  - benjamsf
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Minkä osatehtävän raportti kyseessä?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Listaa, mistä raportti koostuu.
    validations:
      required: true