name: Announce Report Template
description: Post this ticket to announce you have uploaded a Report. 
title: "[Report]: "
labels: ["report"]
projects: ["piasecday/3"]
assignees:
  - benjamsf
body:
  - type: markdown
    attributes:
      value: |
       Minkä osatehtävän raportti?
  - type: textarea
    id: what-happened
    validations:
      required: true