name: Announce Report
description: Post this ticket to announce that you have uploaded a Report. 
title: "[Report]: Task number & Your team name here"
labels: ["report"]
projects: ["piasecday/3"]
assignees:
  - benjamsf
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Mikä raportti kyseessä?
      description: Kirjoita alle. 
    validations:
      required: true